---

- name: Install MySQL Client Core
  apt: name=mysql-client-core-5.6 state=present install_recommends=yes update_cache=yes cache_valid_time=3600
  sudo: yes

- name: Install MySQL Client
  apt: name=mysql-client-5.6 state=present install_recommends=yes update_cache=yes cache_valid_time=3600
  sudo: yes

- name: Install MySQL Server Core
  apt: name=mysql-server-core-5.6 state=present install_recommends=yes update_cache=yes cache_valid_time=3600
  sudo: yes

- name: Install MySQL Server
  apt: name=mysql-server-5.6 state=present install_recommends=yes update_cache=yes cache_valid_time=3600
  sudo: yes

# Ansible needs this to configure MySQL with
- name: Python MySQL driver
  apt: name=python-mysqldb state=present install_recommends=no
  sudo: yes

- name: Create MySQL config file
  action: template src=mysql.my.cnf.j2 dest=/etc/my.cnf
  notify:
    - restart mysql
  sudo: yes

- name: Start MySQL
  service: name=mysql state=started
  sudo: yes

- name: Set MySQL root password
  mysql_user: name=root password={{ mysql_root_password }} host=localhost login_user=root login_password={{ mysql_root_password }} check_implicit_admin=true

- name: Remove MySQL test database
  mysql_db: db=test state=absent login_user=root login_password={{ mysql_root_password }}

- name: Create drupal database
  mysql_db: db={{ drupal_db_name }} state=present login_user=root login_password={{ mysql_root_password }}
  when: drupal_db_name is defined

- name: Create drupal database user
  mysql_user: name={{ drupal_db_user }} password={{ drupal_db_user_pass }} priv="*.*:ALL" state=present login_user=root login_password={{ mysql_root_password }}
  when: drupal_db_user is defined